# Generated by Django 4.1.1 on 2022-09-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
    ]
